version: '3.8'

services:
  backend:
    image: backend
    volumes:
      - ./data:/data
#    deploy:
#      resources:
#        limits:
#          memory: 12g
  frontend:
    image: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend