version: '3.8'

services:
  backend:
    image: backend_twin2
    volumes:
      - ./data:/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - ./frontend/static:/app/static
      - ./frontend/.streamlit:/app/.streamlit
    environment:
      - WATCHDOG_TIMEOUT=10
    depends_on:
      - backend